### ISSUE TITLE
The big bad checklist

### ISSUE THREAD

**Issue by ciaramcguire** [ciaramcguire/Wedding#3]
### Castle
- [x] Booked
- [x] Invoice paid
- [x] Rooming list
### Tito
- [x] Photo(s) selected
- [x] Accommodation blurb
### Consumables
- [x] Menu: discuss with Beth Ann
- [x] Decide on presentation
- [x] Wine: choose
- [x] Wine: ship
- [x] Champagne and prosecco
- [x] Source glasses
- [x] Cocktails
- [x] Coffee
- [x] Coffee nibbles: [gingerbread](http://www.grasmeregingerbread.co.uk/shop/uk/2.htm), [turkish delight](http://www.thesweetspot.ie/hadji-bey-s-original-turkish-delight.html)
- [x] Friday night menu
- [x] Cheese for Friday
- [x] Canapés
- [x] Cake booked
- [x] Cake deposit (20%) paid
- [x] Cake remaining invoice paid - due 23rd November 2013
- [x] Florist input for cake
### Flowers
- [x] Florist for bouquets and buttonholes
- [x] Mum bouquets and corsages
### Boys
- [x] [Suits](http://www.marksandspencer.com/Autograph-Pure-Wool-Button-Jacket/dp/B00BLVKBRY?ie=UTF8&ref=sr_1_1&nodeId=43484030&sr=1-1&qid=1375908337&pf_rd_r=13YQ2PVY0ESVM9FS9MG5&pf_rd_m=A2BO0OYVBKIQJM&pf_rd_t=101&pf_rd_i=43484030&pf_rd_p=321381387&pf_rd_s=related-items-3)
- [x] [Ties](http://www.johnlewis.com/john-lewis-fine-twill-plain-silk-tie/p569816?colour=Bottle%20Green)
- [x] Shirts
- [x] Socks
- [x] Shoes
- [x] Cufflinks
### Girls
- [x] Wedding dress
- [x] Garter
- [x] Jewellery 
- [x] Shoes
- [x] Bridesmaid dress ordered
- [x] Hair piece for Paulina
- [x] Gift for Paulina
- [x] Shoes for Anna
- [x] Headdress for Anna
- [x] Flower girl dress
### Music
- [x] Band
- [x] Decide on set list
- [x] Ceremony music
- [x] Decide on set list
- [ ] Music playlist for Friday and Saturday
### Marquee
- [x] Table plan concept
- [x] Table plan print
- [x] Centre-pieces
- [x] Lighting
- [x] Lining
- [x] Linens 
- [x] Ask about candles
### Print
- [x] Invitations
- [ ] Table plan
- [ ] Table numbers
- [x] Wording
- [x] Approve designs
- [x] Finalise guest list and amass addresses
### Honeymoon
- [x] Pick mini-moon hotel and book Glasgow flights
- [x] Decide on honeymoon destination, flights and accommodation
- [x] Book vaccinations if necessary
- [x] Visa if necessary
### Video
- [x] Meet/Skype [Catch](http://wearecatch.com)
### Photos
- [x] Photographer booked
- [x] What time arriving? 
- [x] Select photo locations (inside and out)
- [x] Shot list finalised
- [x] Remainder of invoice paid
- [x] Engagement session booked
### Details
- [x] Card box, ideally [this one in Small](http://www.oliverbonas.com/homeware/living/bedroom_1/suitcases_set_of_4.htm)
- [x] Guest book - order initials and tags and pens
- [x] AV for speeches
- [ ] Design playlist for during dinner and after Classic Beatles
- [x] Speeches
- [ ] List of thank you's drawn up
- [x] Gift for Dad - [Greenspot 10yr?](http://www.celticwhiskeyshop.com/Greenspot_10_Year_Old_Pure_Pot_Still_Whiskey-z-product-product-70-context-brand-page-1.htm)
- [x] Bridesmaid gift packs and something more lasting (pearls?)
- [x] Robes and slippers
- [x] Garland
- [x] Hire car
- [ ] Ask Sean to pick Paulina up from Cork on Thursday
- [x] Book Thursday night rooms x4
- [x] Buy and pack carby snacks for middle of the night 
### Ceremony
- [x] Readings chosen from [short list](https://github.com/ciaramcguire/Wedding/issues/8)
- [x] Ask people to read
- [x] Strings booked
- [x] Vows
- [x] Music selected
- [x] Timings finalised
- [x] Meet Bill
- [x] Marriage license
- [x] Ask witnesses
### Friday Night
- [x] Menu
- [x] Drink
- [x] Presentation
- [x] Timings
- [ ] Music - design playlist

To do:
- [x] Add Kay to Ballyrafter booking
- [x] Ask about a bed for Tom
- [x] Ask about what sort of wine coolers they have
- [x] Check ring size
- [x] Dessert wine? Dad checking with Christian

**Comment by ciaramcguire** [comment]
Still to do:
- [x] Pay Bill
- [x] Tweak ceremony
- [x] Build seating chart app
- [x] Locate enough iPods and iPads for music and app
- [x] Ask Elizabeth (and Susan?) to read and give them their readings
- [x] Design and print off menu cards
- [x] Get enough paper from Daintree and use their guillotine/scorer
- [x] Write cards for parents, Paulina and Anna
- [x] Wrap gifts for each other (!!!)
- [x] Decide who's Facetiming Niamh!
- [x] Polish and pack champagne coaster from Niamh's wedding
- [x] Confirm number of gin and vodka bottles to get
- [x] Call Sean to set up collection from airport for mum and Paulina, plus weekend shuttles
- [x] Tell Ethel when she's speaking
- [x] Think of something for table names
- [x] Speak to strings about 
- [x] Pay strings
- [x] Hang suits; iron shirt, ties and Anna's sash
- [x] Write list of everything that needs to be brought
- [x] Put ribbon onto tags
- [x] Adjust function sheet (NB add in Gerard's grace)
- [x] Make up a kit of tights, nail files, plasters, sewing kit
- [x] Choose cars, confirm with dad and call Shane to thank him: 0872520787
- [x] Pack!
- [x] Root out ring box for Matthew to use
- [x] Print off nice copies of readings
- [x] Pack printer!!

**Comment by paulca** [comment]
Should we ask Susan to "recite" a song? I feel like that might be nice instead of a stock reading.

**Comment by ciaramcguire** [comment]
Wedding shipped. CLOSING!
